build:
    image: python:2.7
    commands:
        - sleep 5
        - pip install -r requirements.txt
        - pip install .
        - nosetests -v
compose:
    postgres:
        image: postgres:9.4
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
